package com.commai.commaplayer.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.commai.commaplayer.Entity.RecentPlay;

import com.commai.commaplayer.greendao.dao.RecentPlayDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recentPlayDaoConfig;

    private final RecentPlayDao recentPlayDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recentPlayDaoConfig = daoConfigMap.get(RecentPlayDao.class).clone();
        recentPlayDaoConfig.initIdentityScope(type);

        recentPlayDao = new RecentPlayDao(recentPlayDaoConfig, this);

        registerDao(RecentPlay.class, recentPlayDao);
    }
    
    public void clear() {
        recentPlayDaoConfig.clearIdentityScope();
    }

    public RecentPlayDao getRecentPlayDao() {
        return recentPlayDao;
    }

}
